-- WindHero 逐风人 — Supabase schema
-- 在 Supabase SQL Editor 里执行，或在已 link 的本地仓库里跑 `supabase db push`。

create table if not exists public.subscribers (
  id           bigint generated by default as identity primary key,
  email        text not null unique,                 -- 订阅邮箱
  source       text not null default 'site',         -- 订阅来源：site / footer / about 等
  created_at   timestamptz not null default now(),
  confirmed_at timestamptz                           -- 邮箱二次确认时间（暂未启用）
);

create index if not exists subscribers_created_at_idx
  on public.subscribers (created_at desc);

-- 行级安全
alter table public.subscribers enable row level security;

-- 匿名访客可以通过公开 API 写入自己的邮箱，但读不到他人记录。
-- /api/subscribe 用 service-role key 绕过 RLS 做 upsert 与后台查询。
drop policy if exists "anon can subscribe" on public.subscribers;
create policy "anon can subscribe"
  on public.subscribers
  for insert
  to anon
  with check (
    email is not null
    and length(email) between 5 and 254
  );

-- 已登录的后台用户（未来你自己用）才能读全表。
drop policy if exists "auth can read" on public.subscribers;
create policy "auth can read"
  on public.subscribers
  for select
  to authenticated
  using (true);
