-- WindHero — Supabase schema
-- Run this in the Supabase SQL editor (or via `supabase db push`)
-- after pointing `NEXT_PUBLIC_SUPABASE_URL` at your project.

create table if not exists public.subscribers (
  id           bigint generated by default as identity primary key,
  email        text not null unique,
  source       text not null default 'site',
  created_at   timestamptz not null default now(),
  confirmed_at timestamptz
);

create index if not exists subscribers_created_at_idx
  on public.subscribers (created_at desc);

-- Row Level Security
alter table public.subscribers enable row level security;

-- Anonymous visitors can insert their own email via the public API.
-- They may NOT read other rows. The service-role key (used in the API
-- route) bypasses RLS for upserts and admin queries.
drop policy if exists "anon can subscribe" on public.subscribers;
create policy "anon can subscribe"
  on public.subscribers
  for insert
  to anon
  with check (
    email is not null
    and length(email) between 5 and 254
  );

-- Authenticated dashboard users (you, eventually) may read.
drop policy if exists "auth can read" on public.subscribers;
create policy "auth can read"
  on public.subscribers
  for select
  to authenticated
  using (true);
